// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUyJZYbXlwxRbKTj2QWLqWuyolCspb7Ko',
    appId: '1:265196339567:android:e4868cf1b745d96a2be89a',
    messagingSenderId: '265196339567',
    projectId: 'drivessharingapp-175cb',
    databaseURL: 'https://drivessharingapp-175cb-default-rtdb.firebaseio.com',
    storageBucket: 'drivessharingapp-175cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo4GNzkux4FfeG5IzVInSsqIv0FncqOqw',
    appId: '1:265196339567:ios:aa641f3e00c200712be89a',
    messagingSenderId: '265196339567',
    projectId: 'drivessharingapp-175cb',
    databaseURL: 'https://drivessharingapp-175cb-default-rtdb.firebaseio.com',
    storageBucket: 'drivessharingapp-175cb.appspot.com',
    iosBundleId: 'com.example.texiRideSharingAppFlutter',
  );

}